version: '3.9'

services:
  fastapidockercompose:
    build:
      context: .
    container_name: fastapiproject
    ports:
      - 5555:8000
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--reload"]